# Generated by Django 5.1.1 on 2024-09-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('importance', models.IntegerField(help_text='There are 3 levels of importance: 1, 2, 3. 1 is the most important.')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#007bff', help_text='цвет текста', max_length=20)),
                ('background_color', models.CharField(default='#f8f9fa', help_text='цвет фона', max_length=20)),
            ],
        ),
    ]
